name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    -name: Checkout repository
     uses: action/checkout@v2

    -name: Install dependenies\
      run: sudo apt-get install -y g++

    -name: compile C++ code
      run: g++ -o main stack.cpp

    -name: Run the program
      run: ./main
      #Note : If your program requires user input, you might want to handle this differently in a CI environment.
      #For automated testing, consider using a testing framework or redirecting input from a file
